# Generated by Django 4.0.3 on 2022-04-24 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(max_length=65)),
                ('email', models.EmailField(max_length=254, verbose_name='Mail del profesor')),
                ('fecha_contratacion', models.DateField(default=datetime.datetime)),
            ],
        ),
    ]
