# Generated by Django 4.0.3 on 2022-04-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='fecha_contratacion',
            field=models.CharField(max_length=30),
        ),
    ]
