# Generated by Django 4.0.3 on 2022-04-24 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_profesor_fecha_contratacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='fecha_contratacion',
            field=models.DateField(verbose_name=datetime.date(2022, 4, 24)),
        ),
    ]
