# Generated by Django 4.0.3 on 2022-05-22 13:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_escuela_alter_profesor_fecha_contratacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='escuela',
            field=models.ManyToManyField(to='aplicacion.escuela'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.profesor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='escuela',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.escuela'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fecha_contratacion',
            field=models.DateField(verbose_name=datetime.date(2022, 5, 22)),
        ),
    ]
